<?xml version="1.0" encoding="UTF-8"?>
<pages login-view-id="/login.xhtml" no-conversation-view-id="/CustomSearchTopics.xhtml"
	xmlns="http://jboss.com/products/seam/pages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://jboss.com/products/seam/pages http://jboss.com/products/seam/pages-2.2.xsd">
	<page action="#{userPrefs.populate()}" view-id="*" scheme="http">
		<navigation>
			<rule if-outcome="home">
				<redirect view-id="/CustomSearchTopics.xhtml" />
			</rule>
		</navigation>
	</page>
	<page view-id="/CustomSearchTopics.xhtml">
		<navigation>
			<rule>
				<end-conversation before-redirect="true" />
			</rule>
		</navigation>
	</page>
	<exception class="org.jboss.seam.framework.EntityNotFoundException">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Record not found</message>
		</redirect>
	</exception>
	<exception class="javax.persistence.EntityNotFoundException">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Record not found</message>
		</redirect>
	</exception>
	<exception class="javax.persistence.EntityExistsException">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Duplicate record</message>
		</redirect>
	</exception>
	<exception class="javax.persistence.OptimisticLockException">
		<end-conversation />
		<redirect view-id="/error.xhtml">
			<message severity="warn">Another user changed the same data, please try again</message>
		</redirect>
	</exception>
	<exception class="org.jboss.seam.security.AuthorizationException">
		<redirect view-id="/error.xhtml">
			<message severity="error">You don't have permission to access this resource</message>
		</redirect>
	</exception>
	<exception class="org.jboss.seam.security.NotLoggedInException">
		<redirect view-id="/login.xhtml">
			<message severity="warn">#{messages['org.jboss.seam.NotLoggedIn']}</message>
		</redirect>
	</exception>
	<exception class="javax.faces.application.ViewExpiredException">
		<redirect view-id="/login.xhtml">
			<message severity="warn">Your session has timed out, please try again</message>
		</redirect>
	</exception>
	<exception class="org.jboss.seam.ConcurrentRequestTimeoutException"
		log-level="trace">
		<http-error error-code="503" />
	</exception>
	<exception class="com.redhat.topicindex.rest.exceptions.InvalidParameterException">
		<http-error error-code="400">
			<message>#{org.jboss.seam.handledException.message}</message>
		</http-error>
	</exception>
	<exception class="com.redhat.topicindex.rest.exceptions.InternalProcessingException">
		<http-error error-code="500">
			<message>#{org.jboss.seam.handledException.message}</message>
		</http-error>
	</exception>
	<exception>
		<redirect view-id="/error.xhtml">
			<message severity="error">Unexpected error, please try again</message>
		</redirect>
	</exception>
</pages>
